name: "Unity YAML Merge"
author: "AndanteTribe"
description: "A tool to execute YamlMerge for resolving and merging Unity YAML files."

inputs:
  auto-push-remote:
    description: "AUTO_PUSH_REMOTE"
    required: false
  base-branch:
    description: "BASE_BRANCH"
    required: false
  target-extensions:
    description: "TARGET_EXTENSIONS"
    required: false
  project-path:
    description: "PROJECT_PATH"
    required: false
  unity-version-source:
    description: "UNITY_VERSION_SOURCE"
    required: false
  unity-version:
    description: "UNITY_VERSION"
    required: false
runs:
  using: docker
  image: docker://andantetribe/unity-yaml-merge-git:0.1.0-preview7
  args:
    - ${{ inputs.auto-push-remote != '' && '--auto-push' || '' }}
    - ${{ inputs.auto-push-remote }}
  env:
    BASE_BRANCH: ${{ inputs.base-branch }}
    TARGET_EXTENSIONS: ${{ inputs.target-extensions }}
    PROJECT_PATH: ${{ inputs.project-path }}
    UNITY_VERSION_SOURCE: ${{ inputs.unity-version-source }}
    UNITY_VERSION: ${{ inputs.unity-version }}